name: Build PDF.js Generic Viewer

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build generic viewer
        run: npx gulp generic

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdfjs-generic
          path: build/generic
